# Generated by Django 2.2 on 2019-07-19 21:51

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevolvingDoor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=300, verbose_name='Firma')),
                ('crm_no', models.IntegerField(default=0, verbose_name='CRM NO')),
                ('adress', models.CharField(max_length=500, verbose_name='Sevk Adresi')),
                ('delivery_date', models.DateTimeField(verbose_name='Teslim Tarihi')),
                ('delivery_method', models.CharField(max_length=100, verbose_name='Teslim Şekli')),
                ('mr30_type', models.CharField(choices=[('OTOMATİK', 'OTOMATİK'), ('MANUEL', 'MANUEL')], default='OTOMATİK', max_length=30, verbose_name='MR30 Kapı Türü')),
                ('dia', models.IntegerField(default=1600, validators=[django.core.validators.MinValueValidator(1600), django.core.validators.MaxValueValidator(4000)], verbose_name='Çap')),
                ('trans_height', models.IntegerField(default=1900, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(4000)], verbose_name='Geçiş Yüksekliği')),
                ('canopy', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(1500)], verbose_name='Kanopi')),
                ('wing', models.IntegerField(choices=[(3, 3), (4, 4)], default=3, verbose_name='Kanat Sayısı')),
                ('fixed_glass', models.CharField(choices=[('4+4 Bombeli Şeffaf Lamine', '4+4 Bombeli Şeffaf Lamine'), ('5+5 Bombeli Şeffaf Lamine', '5+5 Bombeli Şeffaf Lamine'), ('6+6 Bombeli Şeffaf Lamine', '6+6 Bombeli Şeffaf Lamine'), ('4+4 Bombeli Opak Lamine', '4+4 Bombeli Opak Lamine'), ('5+5 Bombeli Opak Lamine', '5+5 Bombeli Opak Lamine'), ('6+6 Bombeli Opak Lamine', '6+6 Bombeli Opak Lamine')], default='4bombeliseffaflamine', max_length=100, verbose_name='Sabit Cam')),
                ('moving_glass', models.CharField(choices=[('8 mm Temperli', '8 mm Temperli'), ('10 mm Temperli', '10 mm Temperli')], default='8mmtemperli', max_length=100, verbose_name='Hareketli Cam')),
                ('color', models.CharField(choices=[('Ral Boya', 'Ral Boya'), ('Mat Eloksal', 'Mat Eloksal'), ('Renkli Mat Eloksal', 'Renkli Mat Eloksal'), ('304 Kalite Mat', '304 Kalite Mat'), ('304 Kalite Ayna', '304 Kalite Ayna'), ('304 Kalite Satina', '304 Kalite Satina'), ('316 Kalite Mat', '316 Kalite Mat'), ('316 Kalite Ayna', '316 Kalite Ayna'), ('316 Kalite Satina', '316 Kalite Satina')], default='mateloksal', max_length=100, verbose_name='Renk')),
                ('lighting', models.CharField(choices=[('Halojen Spot Camlı', 'Halojen Spot Camlı'), ('Halojen Spot Camsız', 'Halojen Spot Camsız'), ('Led Spot', 'Led Spot')], default='ledspot', max_length=50, verbose_name='Işıklandırma')),
                ('broken_wing', models.BooleanField(default=False, verbose_name='Kırılan Kanat')),
                ('ground_circle', models.BooleanField(default=False, verbose_name='Yer Çemberi')),
                ('night_sensor', models.BooleanField(default=False, verbose_name='Gece Kalkanı')),
                ('heel_sensor', models.BooleanField(default=False, verbose_name='Topuk Sensörü')),
                ('hand_sensor', models.BooleanField(default=False, verbose_name='El Sensörü')),
                ('spot_scan', models.BooleanField(default=False, verbose_name='Spot Scan')),
                ('spain_key', models.BooleanField(default=False, verbose_name='İspanyolet Kilit')),
                ('stain_arm', models.BooleanField(default=False, verbose_name='Paslanmaz Kol')),
                ('button_pole', models.BooleanField(default=False, verbose_name='Buton Direği')),
                ('notes', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Notlar')),
                ('drawing', models.CharField(max_length=200, verbose_name='Yazar')),
                ('control', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kontrol')),
                ('manufacturing_chief', models.CharField(blank=True, max_length=200, null=True, verbose_name='İmalat Şefi')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'MR30/SA DÖNER KAPI',
                'ordering': ['-id'],
            },
        ),
    ]
