# Generated by Django 2.2 on 2019-07-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RevolvingDoor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=300, verbose_name='Firma')),
                ('crm_no', models.CharField(max_length=50, verbose_name='CRM No')),
                ('adress', models.TextField(verbose_name='Sevk Adresi')),
                ('delivery_date', models.DateTimeField(verbose_name='Teslim Tarihi')),
                ('delivery_method', models.CharField(max_length=100, verbose_name='Teslim Şekli')),
                ('dia', models.CharField(max_length=20, verbose_name='Çap')),
                ('trans_height', models.CharField(max_length=20, verbose_name='Geçiş Yüksekliği')),
                ('canopy', models.CharField(max_length=20, verbose_name='Kanopi')),
                ('total_height', models.CharField(max_length=20, verbose_name='Toplam Yükseklik')),
                ('wing', models.IntegerField(default=0, verbose_name='Kanat Sayısı')),
                ('fixed_glass', models.CharField(max_length=100, verbose_name='Sabit Cam')),
                ('moving_glass', models.CharField(max_length=100, verbose_name='Hareketli Cam')),
                ('glass1', models.CharField(max_length=20, verbose_name='Cam')),
                ('glass2', models.CharField(max_length=100, verbose_name='Cam')),
                ('color', models.CharField(max_length=100, verbose_name='Renk')),
                ('lighting', models.CharField(max_length=50, verbose_name='Işıklandırma')),
                ('broken_wing', models.BooleanField(default=False, verbose_name='Kırılan Kanat')),
                ('ground_circle', models.BooleanField(default=False, verbose_name='Yer Çemberi')),
                ('night_sensor', models.BooleanField(default=False, verbose_name='Gece Kalkanı')),
                ('heel_sensor', models.BooleanField(default=False, verbose_name='Topuk Sensörü')),
                ('hand_sensor', models.BooleanField(default=False, verbose_name='El Sensörü')),
                ('spot_scan', models.BooleanField(default=False, verbose_name='Spot Scan')),
                ('spain_key', models.BooleanField(default=False, verbose_name='İspanyolet Kilit')),
                ('stain_arm', models.BooleanField(default=False, verbose_name='Paslanmaz Kol')),
                ('button_pole', models.BooleanField(default=False, verbose_name='Buton Direği')),
                ('note1', models.CharField(blank=True, max_length=300, null=True, verbose_name='Not 1')),
                ('note2', models.CharField(blank=True, max_length=300, null=True, verbose_name='Not 2')),
                ('note3', models.CharField(blank=True, max_length=300, null=True, verbose_name='Not 3')),
                ('note4', models.CharField(blank=True, max_length=300, null=True, verbose_name='Not 4')),
                ('note5', models.CharField(blank=True, max_length=300, null=True, verbose_name='Not 5')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'MR30/SA OTOMATİK DÖNER KAPI',
                'ordering': ['-id'],
            },
        ),
    ]
