# Generated by Django 2.2 on 2019-07-15 10:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RevolvingDoor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=300, verbose_name='Firma')),
                ('adress', ckeditor.fields.RichTextField(verbose_name='Sevk Adresi')),
                ('delivery_date', models.DateTimeField(verbose_name='Teslim Tarihi')),
                ('delivery_method', models.CharField(max_length=100, verbose_name='Teslim Şekli')),
                ('dia', models.IntegerField(default=0, verbose_name='Çap')),
                ('trans_height', models.IntegerField(default=0, verbose_name='Geçiş Yüksekliği')),
                ('canopy', models.IntegerField(default=0, verbose_name='Kanopi')),
                ('wing', models.IntegerField(default=0, verbose_name='Kanat Sayısı')),
                ('fixed_glass', models.CharField(choices=[('4bombeliseffaflamine', '4+4 Bombeli Şeffaf Lamine'), ('4bombeliseffaflamine', '5+5 Bombeli Şeffaf Lamine'), ('4bombeliseffaflamine', '6+6 Bombeli Şeffaf Lamine'), ('4bombeliopaklamine', '4+4 Bombeli Opak Lamine'), ('4bombeliopaklamine', '5+5 Bombeli Opak Lamine'), ('4bombeliopaklamine', '6+6 Bombeli Opak Lamine')], default='4bombeliseffaflamine', max_length=100, verbose_name='Sabit Cam')),
                ('moving_glass', models.CharField(choices=[('8mmtemperli', '8 mm Temperli'), ('10mmtemperli', '10 mm Temperli')], default='8mmtemperli', max_length=100, verbose_name='Hareketli Cam')),
                ('fixed_glass_no', models.IntegerField(default=0, verbose_name='Sabit Cam Sayısı')),
                ('moving_glass_no', models.IntegerField(default=0, verbose_name='Hareketli Cam Sayısı')),
                ('color', models.CharField(choices=[('ralboya', 'Ral Boya'), ('mateloksal', 'Mat Eloksal'), ('renklimateloksal', 'Renkli Mat Eloksal'), ('304kalitemat', '304 Kalite Mat'), ('304kaliteayna', '304 Kalite Ayna'), ('304kalitesatina', '304 Kalite Satina'), ('316kalitemat', '316 Kalite Mat'), ('316kaliteayna', '316 Kalite Ayna'), ('316kalitesatina', '316 Kalite Satina')], default='mateloksal', max_length=100, verbose_name='Renk')),
                ('lighting', models.CharField(choices=[('halojenspotcamli', 'Halojen Spot Camlı'), ('halojenspotcamsiz', 'Halojen Spot Camsız'), ('ledspot', 'Led Spot')], default='ledspot', max_length=50, verbose_name='Işıklandırma')),
                ('broken_wing', models.BooleanField(default=False, verbose_name='Kırılan Kanat')),
                ('ground_circle', models.BooleanField(default=False, verbose_name='Yer Çemberi')),
                ('night_sensor', models.BooleanField(default=False, verbose_name='Gece Kalkanı')),
                ('heel_sensor', models.BooleanField(default=False, verbose_name='Topuk Sensörü')),
                ('hand_sensor', models.BooleanField(default=False, verbose_name='El Sensörü')),
                ('spot_scan', models.BooleanField(default=False, verbose_name='Spot Scan')),
                ('spain_key', models.BooleanField(default=False, verbose_name='İspanyolet Kilit')),
                ('stain_arm', models.BooleanField(default=False, verbose_name='Paslanmaz Kol')),
                ('button_pole', models.BooleanField(default=False, verbose_name='Buton Direği')),
                ('notes', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Notlar')),
                ('drawing_name', models.CharField(max_length=200, verbose_name='Çizim')),
                ('control_name', models.CharField(max_length=200, verbose_name='Kontrol')),
                ('manufacturing_chief', models.CharField(max_length=200, verbose_name='İmalat Şefi')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'MR30/SA OTOMATİK DÖNER KAPI',
                'ordering': ['-id'],
            },
        ),
    ]
