# Generated by Django 2.2 on 2019-07-15 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revolvingdoor',
            old_name='control_name',
            new_name='control',
        ),
        migrations.RenameField(
            model_name='revolvingdoor',
            old_name='drawing_name',
            new_name='drawing',
        ),
    ]
