# Generated by Django 2.2 on 2019-07-21 08:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingridients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_code', models.CharField(max_length=100, verbose_name='Renk Kodu')),
            ],
        ),
        migrations.AlterField(
            model_name='revolvingdoor',
            name='control',
            field=models.CharField(blank=True, default=datetime.datetime(2019, 7, 21, 8, 43, 45, 101772, tzinfo=utc), max_length=200, verbose_name='Kontrol'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='revolvingdoor',
            name='manufacturing_chief',
            field=models.CharField(blank=True, default=1, max_length=200, verbose_name='İmalat Şefi'),
            preserve_default=False,
        ),
    ]
