# Generated by Django 2.2 on 2019-07-13 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revolvingdoor',
            name='total_height',
        ),
    ]
