# Generated by Django 2.2 on 2019-07-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revolvingdoor',
            name='note1',
        ),
        migrations.RemoveField(
            model_name='revolvingdoor',
            name='note2',
        ),
        migrations.RemoveField(
            model_name='revolvingdoor',
            name='note3',
        ),
        migrations.RemoveField(
            model_name='revolvingdoor',
            name='note4',
        ),
        migrations.RemoveField(
            model_name='revolvingdoor',
            name='note5',
        ),
        migrations.AddField(
            model_name='revolvingdoor',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notlar'),
        ),
    ]
