# Generated by Django 2.2 on 2019-07-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20190715_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revolvingdoor',
            name='adress',
            field=models.CharField(max_length=500, verbose_name='Sevk Adresi'),
        ),
    ]
