# Generated by Django 2.2 on 2019-07-07 19:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20190707_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revolvingdoor',
            name='glass1',
        ),
        migrations.RemoveField(
            model_name='revolvingdoor',
            name='glass2',
        ),
        migrations.AddField(
            model_name='revolvingdoor',
            name='fixed_glass_no',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, verbose_name='Sabit Cam Sayısı'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revolvingdoor',
            name='moving_glass_no',
            field=models.CharField(default=datetime.datetime(2019, 7, 7, 19, 4, 37, 948727, tzinfo=utc), max_length=100, verbose_name='Hareketli Cam Sayısı'),
            preserve_default=False,
        ),
    ]
