# Generated by Django 2.2 on 2019-07-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20190721_1143'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingridients',
        ),
        migrations.AddField(
            model_name='revolvingdoor',
            name='ral_color_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ral Boya İçin Renk Kodu'),
        ),
    ]
