# Generated by Django 2.2 on 2019-07-07 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20190707_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revolvingdoor',
            name='delivery_date',
        ),
    ]
