# Generated by Django 2.2 on 2019-07-09 08:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_revolvingdoor_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='revolvingdoor',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 8, 22, 37, 680742, tzinfo=utc), verbose_name='Teslim Tarihi'),
            preserve_default=False,
        ),
    ]
