# Generated by Django 2.2 on 2019-07-16 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_revolvingdoor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revolvingdoor',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
