# Generated by Django 2.2 on 2019-07-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_revolvingdoor_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revolvingdoor',
            name='canopy',
            field=models.IntegerField(max_length=20, verbose_name='Kanopi'),
        ),
        migrations.AlterField(
            model_name='revolvingdoor',
            name='dia',
            field=models.IntegerField(max_length=20, verbose_name='Çap'),
        ),
        migrations.AlterField(
            model_name='revolvingdoor',
            name='fixed_glass_no',
            field=models.IntegerField(max_length=20, verbose_name='Sabit Cam Sayısı'),
        ),
        migrations.AlterField(
            model_name='revolvingdoor',
            name='moving_glass_no',
            field=models.IntegerField(max_length=100, verbose_name='Hareketli Cam Sayısı'),
        ),
        migrations.AlterField(
            model_name='revolvingdoor',
            name='total_height',
            field=models.IntegerField(max_length=20, verbose_name='Toplam Yükseklik'),
        ),
    ]
