# Generated by Django 2.2 on 2019-07-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20190709_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revolvingdoor',
            name='trans_height',
            field=models.IntegerField(default=0, verbose_name='Geçiş Yüksekliği'),
        ),
    ]
