# Generated by Django 2.2 on 2019-07-09 23:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20190710_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revolvingdoor',
            name='adress',
            field=ckeditor.fields.RichTextField(verbose_name='Sevk Adresi'),
        ),
        migrations.AlterField(
            model_name='revolvingdoor',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Notlar'),
        ),
    ]
